services:
  # Nginx Service
  - name: nginx
    type: web
    runtime: docker
    dockerfilePath: ./app/nginx/Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 80

  # MongoDB Service (use Render's managed MongoDB if possible)
  - name: mongo
    type: worker
    runtime: docker
    autoDeploy: true
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: root
      - key: MONGO_INITDB_ROOT_PASSWORD
        value: rootpassword

  # Backend Service
  - name: backend
    type: web
    runtime: docker
    dockerfilePath: ./app/backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: "mongodb://root:rootpassword@mongo:27017/campuslink_db?authSource=admin"
      - key: PORT
        value: 5000

  # Frontend Service
  - name: frontend
    type: web
    runtime: docker
    dockerfilePath: ./app/frontend/Dockerfile
    buildCommand: npm run build
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

  # Ollama Service
  - name: ollama
    type: worker
    runtime: docker
    autoDeploy: true
