version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./backend/uploads:/app/uploads:ro
    depends_on:
      - frontend
      - backend
      - ollama

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    env_file:
      - ./.env
    environment:
      DATABASE_URL: "mongodb://root:rootpassword@mongo:27017/campuslink_db?authSource=admin"
      PORT: 5000
    depends_on:
      - mongo
    ports:
      - '5000:5000'
    tty: true
    volumes:
      - ./backend:/src
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/src

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/data
    restart: always

volumes:
  mongo_data:
  uploads-data:
  ollama_data:
